/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veterinaria;

import java.util.List;
import javax.swing.JTextArea;

/**
 *
 * @author Eddier
 */
public class Menu extends javax.swing.JFrame {
    private Funciones funciones;
    private Grafo grafo;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        funciones = new Funciones(txaDatos);
        grafo = new Grafo(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregarMascota = new javax.swing.JButton();
        btnMostrarMascotaYVacunas = new javax.swing.JButton();
        btnAgregarCita = new javax.swing.JButton();
        btnMostrarCita = new javax.swing.JButton();
        btnMostrarInOrden = new javax.swing.JButton();
        btnDesencolarCita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDatos = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnMostrarTratamiento = new javax.swing.JButton();
        btnAgregarTratamiento = new javax.swing.JButton();
        btnMostrarGrafo = new javax.swing.JButton();
        btnBuscarTratamiento = new javax.swing.JButton();
        btnModificarTratamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/salud.png"))); // NOI18N
        jLabel1.setText("Veterinaria ");

        btnAgregarMascota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/agregar.png"))); // NOI18N
        btnAgregarMascota.setText("Agregar Mascota");
        btnAgregarMascota.setPreferredSize(new java.awt.Dimension(155, 26));
        btnAgregarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMascotaActionPerformed(evt);
            }
        });

        btnMostrarMascotaYVacunas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarMascotaYVacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/mostrar.png"))); // NOI18N
        btnMostrarMascotaYVacunas.setText("Mostrar Mascotas ");
        btnMostrarMascotaYVacunas.setPreferredSize(new java.awt.Dimension(155, 26));
        btnMostrarMascotaYVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMascotaYVacunasActionPerformed(evt);
            }
        });

        btnAgregarCita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/perrito.png"))); // NOI18N
        btnAgregarCita.setText("Agregar Cita ");
        btnAgregarCita.setMaximumSize(new java.awt.Dimension(155, 26));
        btnAgregarCita.setPreferredSize(new java.awt.Dimension(155, 26));
        btnAgregarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCitaActionPerformed(evt);
            }
        });

        btnMostrarCita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/mostrar (1).png"))); // NOI18N
        btnMostrarCita.setText("Mostrar Cola de Citas");
        btnMostrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCitaActionPerformed(evt);
            }
        });

        btnMostrarInOrden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarInOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/ascendencia.png"))); // NOI18N
        btnMostrarInOrden.setText("Mostrar Arbol In Orden");
        btnMostrarInOrden.setPreferredSize(new java.awt.Dimension(143, 26));
        btnMostrarInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInOrdenActionPerformed(evt);
            }
        });

        btnDesencolarCita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDesencolarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/eliminar-producto.png"))); // NOI18N
        btnDesencolarCita.setText("Desencolar Citas");
        btnDesencolarCita.setToolTipText("");
        btnDesencolarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesencolarCitaActionPerformed(evt);
            }
        });

        txaDatos.setColumns(20);
        txaDatos.setForeground(new java.awt.Color(204, 204, 255));
        txaDatos.setRows(5);
        jScrollPane1.setViewportView(txaDatos);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/fregona.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnMostrarTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/vitamina.png"))); // NOI18N
        btnMostrarTratamiento.setText("Mostrar Tratamientos");
        btnMostrarTratamiento.setMaximumSize(new java.awt.Dimension(155, 26));
        btnMostrarTratamiento.setPreferredSize(new java.awt.Dimension(155, 26));
        btnMostrarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTratamientoActionPerformed(evt);
            }
        });

        btnAgregarTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/pastillas.png"))); // NOI18N
        btnAgregarTratamiento.setText("Agregar Tratamiento");
        btnAgregarTratamiento.setMaximumSize(new java.awt.Dimension(155, 26));
        btnAgregarTratamiento.setPreferredSize(new java.awt.Dimension(155, 26));
        btnAgregarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTratamientoActionPerformed(evt);
            }
        });

        btnMostrarGrafo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarGrafo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/tienda-de-animales.png"))); // NOI18N
        btnMostrarGrafo.setText("Mostrar Grafo");
        btnMostrarGrafo.setMaximumSize(new java.awt.Dimension(155, 26));
        btnMostrarGrafo.setPreferredSize(new java.awt.Dimension(155, 26));
        btnMostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGrafoActionPerformed(evt);
            }
        });

        btnBuscarTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/registros-medicos.png"))); // NOI18N
        btnBuscarTratamiento.setText("Buscar Tratamiento");
        btnBuscarTratamiento.setMaximumSize(new java.awt.Dimension(155, 26));
        btnBuscarTratamiento.setPreferredSize(new java.awt.Dimension(155, 26));
        btnBuscarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTratamientoActionPerformed(evt);
            }
        });

        btnModificarTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/cita-en-linea.png"))); // NOI18N
        btnModificarTratamiento.setText("Modificar Tratamiento");
        btnModificarTratamiento.setMaximumSize(new java.awt.Dimension(155, 26));
        btnModificarTratamiento.setPreferredSize(new java.awt.Dimension(155, 26));
        btnModificarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTratamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgregarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMostrarMascotaYVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMostrarInOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDesencolarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnMostrarGrafo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarCita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMostrarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(btnMostrarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarMascotaYVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(btnModificarTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarInOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesencolarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMascotaActionPerformed
        funciones.agregarMascota();
    }//GEN-LAST:event_btnAgregarMascotaActionPerformed

    private void btnMostrarMascotaYVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMascotaYVacunasActionPerformed
        funciones.mostrarMascotas();
    }//GEN-LAST:event_btnMostrarMascotaYVacunasActionPerformed

    private void btnAgregarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCitaActionPerformed
        funciones.agregarCola();
    }//GEN-LAST:event_btnAgregarCitaActionPerformed

    private void btnMostrarInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInOrdenActionPerformed
        funciones.mostrarArbolBinario();
    }//GEN-LAST:event_btnMostrarInOrdenActionPerformed

    private void btnMostrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCitaActionPerformed
        funciones.mostrarCola();
    }//GEN-LAST:event_btnMostrarCitaActionPerformed

    private void btnDesencolarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesencolarCitaActionPerformed
        funciones.desencolar();
    }//GEN-LAST:event_btnDesencolarCitaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txaDatos.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMostrarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTratamientoActionPerformed
        funciones.mostrarTratamientos();
    }//GEN-LAST:event_btnMostrarTratamientoActionPerformed

    private void btnAgregarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTratamientoActionPerformed
        funciones.agregarTratamiento();
    }//GEN-LAST:event_btnAgregarTratamientoActionPerformed

    private void btnMostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGrafoActionPerformed
            // Inicializar datos del grafo
            grafo.asignarNombre(0, "Veterinaria");
            grafo.asignarNombre(1, "Supermercado");
            grafo.asignarNombre(2, "Colegio");
            grafo.asignarNombre(3, "Banco");
            grafo.asignarNombre(4, "Hospital");

            // Agregar conexiones
            grafo.agregar(0, 1);
            grafo.agregar(0, 2);
            grafo.agregar(1, 0);
            grafo.agregar(1, 3);
            grafo.agregar(1, 4);
            grafo.agregar(2, 0);
            grafo.agregar(2, 3);
            grafo.agregar(2, 4);
            grafo.agregar(3, 1);
            grafo.agregar(3, 2);
            grafo.agregar(4, 1);
            grafo.agregar(4, 2);

            // Imprimir el grafo
            grafo.imprimir(txaDatos);
            for (int i = 0; i < 5; i++) {
                grafo.mostrarRutas(i, txaDatos);
            }
    }//GEN-LAST:event_btnMostrarGrafoActionPerformed

    private void btnBuscarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTratamientoActionPerformed
        funciones.buscarTratamiento();
    }//GEN-LAST:event_btnBuscarTratamientoActionPerformed

    private void btnModificarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTratamientoActionPerformed
        funciones.modificarTratamiento();
    }//GEN-LAST:event_btnModificarTratamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCita;
    private javax.swing.JButton btnAgregarMascota;
    private javax.swing.JButton btnAgregarTratamiento;
    private javax.swing.JButton btnBuscarTratamiento;
    private javax.swing.JButton btnDesencolarCita;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarTratamiento;
    private javax.swing.JButton btnMostrarCita;
    private javax.swing.JButton btnMostrarGrafo;
    private javax.swing.JButton btnMostrarInOrden;
    private javax.swing.JButton btnMostrarMascotaYVacunas;
    private javax.swing.JButton btnMostrarTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDatos;
    // End of variables declaration//GEN-END:variables
}
